# Generated by Django 3.0 on 2021-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClgApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='usrole',
            field=models.IntegerField(choices=[(2, 'HOD'), (1, 'Student'), (3, 'Guest')], default=3),
        ),
    ]
